// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ArticleContent: typeof import('./src/components/article-content/article-content.vue')['default']
    ArticleContentItem: typeof import('./src/components/article-content/article-content-item.vue')['default']
    AsideBar: typeof import('./src/components/aside-bar/aside-bar.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTag: typeof import('element-plus/es')['ElTag']
    FontIcon: typeof import('./src/components/Icon/src/FontIcon.vue')['default']
    NavBar: typeof import('./src/components/nav-bar/nav-bar.vue')['default']
    SendVCodeBtn: typeof import('./src/components/SendVCodeBtn/src/SendVCodeBtn.vue')['default']
    SvgIcon: typeof import('./src/components/Icon/src/SvgIcon.vue')['default']
  }
}

export { }
